### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms.

### ISSUE THREAD

**Issue by EnoxSoftware** [cafeeyen/WorldofMotion#14]
Hi.
I am a developer of "OpenCVForUnity".
Your public repository contains the files of the paid Unity asset that I am selling in the asset store.
Could you add the "OpenCVForUnity" folder to the .ignore file or change the attribute of the repository to private?
I hope that you will understand.
Thank you in advance.

Enox Software

**Comment by cafeeyen** [comment]
Hi.
I apologize for the mistake. Totally forgot about it.
Currently add this to .gitignore and completely remove from repo history.

Sincerely,
Cafeeyen

**Comment by EnoxSoftware** [comment]
Thank you for your quick and polite response.
